services:
  faster-whisper:
    image: ghcr.io/speaches-ai/speaches:0.9.0-rc.3-cuda
    container_name: faster-whisper
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "127.0.0.1:10300:10300"
    environment:
      - WHISPER__INFERENCE_DEVICE=cuda
      - WHISPER__COMPUTE_TYPE=float16
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=10300
      - PRELOAD_MODELS=["Systran/faster-whisper-large-v3"]
    volumes:
      - faster-whisper-models:/home/ubuntu/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  faster-whisper-models:
